test/unit/feedbackController_spec.js, test/unit/feedbackView_spec.html, test/unit/feedbackView_spec.js, views/room.ejs, web/js/feedbackController.js, web/js/feedbackView.js, web/less/room.less
This adds a button that implements the [reportIssue API.](https://tokbox.com/developer/guides/debugging/js/#report-issue)
=> Add report issue button.

web/js/roomController.js
This PR solves the problem of hangup button and functionality when google auth is not required (and therefore token values are "" which caused the issues).
=> [ECO-1038] Fix hangup button when no google auth

web/js/helpers/opentok-network-test.js, web/js/precallController.js
Changing the network test to use its own publisher, not the on-screen preview publisher.
=> Network test fixes -  ECO-1051, ECO-1052

server/serverMethods.js, test/unit/chatController_spec.js, test/unit/chatView_spec.js, web/js/chatController.js, web/js/chatView.js, web/js/helpers/requests.js, web/js/landingView.js, web/js/roomController.js
We should test this rigorously, any issues could break any API requests.
=> [ECO-1135] Escape special characters in room name

web/js/roomController.js
See https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher.
=> Remove previous device selection for room publisher in IE

views/index.ejs, web/less/landing.less
Also, have the bottom padding of the intro form match the top.
=> Fix CSS on landing page when the heading text is present.

web/js/components/modal.js, web/js/landingView.js
Modal dialog boxes should remove focus from background elements when
displayed
=> ECO-1190 - Fixes enter key issue with landing page ToS form

test/unit/chatController_spec.js, test/unit/chatView_spec.js, web/js/chatController.js, web/js/chatView.js
2nd attempt. 1st try didn't account for chat history.
=> [ECO-1005] Fix chat to differentiate between users of same username

web/templates/precall.ejs
Autocomplete is causing yellow and white fields to appear on precall name field. This disrupts the visual style and looks weird. Updated the field to not autocomplete.
See https://tokbox.atlassian.net/browse/ECO-1361
=> [ECO-1361]

package.json
Checked here and all fine https://opentokdemo-tbrel.herokuapp.com/
=> Deploy Tbrel to Master

README.md, package-lock.json, package.json, server/serverConstants.js, server/serverMethods.js, views/room.ejs, web/js/helpers/OTHelper.js, web/js/phoneNumberView.js, web/js/roomController.js
* Add config parameter for the OpenTok.js URL 
* Load JQuery from googleapis.com
=> Minor update 3.0.1

README.md, package-lock.json, package.json, server/serverConstants.js, server/serverMethods.js, views/room.ejs, web/js/helpers/OTHelper.js, web/js/phoneNumberView.js, web/js/roomController.js
* Add config parameter for the OpenTok.js URL (#462)
* Load JQuery from googleapis.com (#461)
=> Minor update - 3.0.1

server/serverMethods.js, views/room.ejs
This PR is meant to replace https://github.com/opentok/OpenTokRTC-V2/pull/474.
=> Set domain name from config var in prompt for SIP dial-out authorization

README.md, api.yml, package-lock.json, package.json, server/firebaseArchives.js, server/serverMethods.js, server/testHealth.js, test/api/server_spec.js
You can ping /server/health to check that the app is able to connect to all required external services
=> Adding a health check endpoint

screen-sharing-extension-chrome/content-script.js, test/unit/roomView_spec.html, test/unit/screenShareController_spec.js, test/unit/screenShareView_spec.html, test/unit/screenShareView_spec.js, views/min.ejs, views/room.ejs, web/js/screenShareController.js, web/js/screenShareView.js
Reverts opentok/opentok-rtc#485
=> Revert "[ECO-3440] Remove deprecated chrome.webstore.install"

web/less/layout.less
https://tokbox.atlassian.net/browse/ECO-3893
=> Dont allow device name to overflow out of container

web/js/landingView.js, web/js/precallController.js
https://tokbox.atlassian.net/browse/ECO-3773
=> Remember user name

web/less/annotation.less, web/less/chat.less, web/less/room.less
I cant see the bottom controls bar locally, Confirm that this solves the described problems in the ticket before merging
=> [ECO-4785]  Vonage brand colors (DONT MERGE)

web/less/room.less
I cant see the bottom controls bar locally, Confirm that this solves the described problems in the ticket before merging
=> [ECO-4796] Show complete url in invite (DONT MERGE)

web/js/landingView.js
=> fix(landingView): room navigation will now handle query string

web/less/landing.less, web/less/room.less
Add scrolling support for landing page and pre-call page
=> [ECO-4832] Allow pages on freeconferencing to scroll

api.yml, server/serverMethods.js, web/js/landingView.js, web/js/libs/browser_utils.js, web/js/roomController.js
The chars are excluded from "username" and "room" inputs after security team feedback
=> Added middleware to set security headers and excluded more special chars

README.md, config/example.json, server/serverConstants.js, server/serverMethods.js, views/room.ejs
... for Mute All and Stop Receiving Video.
=> Add config/env settings to disable top menu UI controls

views/index.ejs, web/js/landingView.js, web/less/landing.less
=> Remove duplicate join meeting button in landing view

README.md, config/example.json
Minor Cleanup of Readme:
- Update signup links for Tokbox & Nexmo
- Removed Chrome extension documentation & added comments for legacy implementation
- Minor formating changes
=> Readme updates

.github/workflows/main.yml
Adding a GitHub action to record repo metrics to Firestore
=> Adding action workflow for Aggregit to record metrics

api.yml, package-lock.json, package.json, server/serverMethods.js
**What is this PR doing?**
It configures HTTP security headers for the app.
**Note:** CSP was not added because the app is currently loading scripts from CDN's.
=> [ECO-4623] - Add security headers

web/less/base.less, web/less/icons.less, web/less/landing.less, web/less/layout.less, web/less/room.less, web/less/variables.less
[5592](https://tokbox.atlassian.net/browse/ECO-5592)
Fixed intro page to display properly in landscape mode and tested in multiple devices 
[5594](https://tokbox.atlassian.net/browse/ECO-5594)
Scroll is fixed with new slim header and added extra css to force not to scroll  in landscape mode
[5595](https://tokbox.atlassian.net/browse/ECO-5595)
The new header displays menu at the right place
=> ECO-5592 , ECO-5595, ECO-5599

web/less/base.less, web/less/room.less
- Stale variables from multi PR requests fixed.
- Validated features in local
=> Hot fix eco5596 eco5613

views/endMeeting.ejs, views/index.ejs, views/min.ejs, views/room.ejs, web/less/base.less
ability to scroll the terms and conditions page is enabled in landscape mode 
- verified in iPhone X
- verified in iPhone 8
=> Scroll Contract modal in landscape

web/less/annotation.less, web/less/base.less, web/less/bubble.less, web/less/buttons.less, web/less/chat.less, web/less/endMeeting.less, web/less/landing.less, web/less/layout.less, web/less/min.less, web/less/room.less, web/less/tooltips.less, web/less/variables.less
- isolated variables in the variables file
=> ECO-4901 Define colors in variables.less throughout

.github/workflows/delete-closed-pr.yml
This workflow enables deleting merged or closed PRs
=> Deleted merged/closed PRS

views/room.ejs
[ECO 5807](https://tokbox.atlassian.net/browse/ECO-5807)
=> ECO 5807 - remove deprecated mobile browser detection 

web/js/rtcApp.js
All paths use the RoomController.
=> Simplify the rtcApp.js file

views/room.ejs
- annotation css loads only when required as per the functionality
=> ECO 5682 - issue with annotation css fixed

web/js/vendor/opentok-annotation.js
- verify before adding tools to DOM
- add only when it doesn't exist
[ECO-5827](https://tokbox.atlassian.net/browse/ECO-5827)
=> ECO 5827 - Duplicate tools on subsequent screen sharing fixed

web/less/precall.less, web/less/room.less
This PR fixes issues related to styles
[ECO-5914](https://tokbox.atlassian.net/browse/ECO-5914)
[ECO-5913](https://tokbox.atlassian.net/browse/ECO-5913)
=> ECO 5913 & ECO 5914 - fix style issues

README.md
Correcting wrong environment variable :-
export TB_API_KEY=<key>
export TB_API_SECRET=<secret>
=> export TB_API_KEY=<key> export TB_API_KEY=<secret>
